site_name: Dr. Kareem Jaradat
site_url: http://jaradat.ca
theme:
  name: material
  custom_dir: overrides
  font:
    text: open sans
    code: Red Hat Mono
  logo: assets/knife.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path #breadcrumbs
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
  # icon:
    # logo: fontawesome/solid/w
  favicon: assets/knife.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo #blue grey
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
      
plugins: 
  - typeset
  - search

markdown_extensions:
  # Emoji and icons
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # code formatting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  #content tabs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.tabbed:
      alternate_style: true
  #admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  #table of contents
  - toc:
      title: 'On this page <br><br>'
      permalink: true
      toc_depth: 2 # 0 -> hidden,2 -> upto ##, 3 -> upto ###

#Footer
copyright: Copyright &copy; 2026 Kareem Jaradat
extra:
  generator: false
  social:
    - icon: fontawesome/brands/square-linkedin 
      link: https://www.linkedin.com/in/abedjar/
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=y1XN-iQAAAAJ&hl=en
    - icon: simple/researchgate
      link: https://www.researchgate.net/profile/Kareem-Jaradat
    - icon: simple/orcid
      link: https://orcid.org/0000-0002-2694-884X
nav:
  - Home: index.md
  - About: 
      - Biography: about/bio.md
      - Resume: about/resume.md
      - Contact: about/contact.md
  - Research:
      - Overview: research/overview.md
      - Projects: research/projects.md
      - Publications: research/publications.md
      - Grants & Awards: research/grants.md
      - Prospective Students: research/students.md
  - Teaching:
      - Courses: teaching/courses.md
      - Teaching Philosophy: teaching/philosophy.md
      - EDID Principles: teaching/edid.md

  # - About: 
  #   - about/index.md
  #   - Biography: about/bio.md
  #   - Resume: about/resume.md
  #   - Contact: about/contact.md

  # - Service: service/service.md
  # - Media: media/media.md


# <script defer src="https://cloud.umami.is/script.js" data-website-id="f1012d34-509c-42f7-8f38-41f26889a96f"></script>